name: Greet New Contributors

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello and welcome! Thank you for your first pull request. We appreciate your contribution!
